# Generated by Django 2.0.2 on 2018-12-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['c_time'], 'verbose_name': '话题', 'verbose_name_plural': '话题'},
        ),
    ]
